# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3d605393ee6df957422cc1cb48b4c2a6f7e93a5fec48d47e87b5413bbe661e79cd2ef4b15fdfb0192bbaad4336f7cf63210227470f7b8472c0ed759e7e71279

test:
  secret_key_base: 0f184cba87fc46990693367d8a506e9639de9ed7a005a3904a93329aa75686b110b7756b5ac0f286807b9b764e5d15d7a7a2b435a31f4b5d4526894bbf17a6c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
